### ISSUE TITLE
multiline string not highlighted correctly

### ISSUE THREAD

**Issue by flynfish** [atom/language-yaml#10]
The following mult-line string does not highlight correctly:

![screen shot 2014-08-06 at 12 37 36 pm](https://cloud.githubusercontent.com/assets/253936/3831894/c82e0400-1d98-11e4-8919-5f9c7c81e2d6.png)

Using the `>` character it's highlighted correctly, but I'd rather not use the `>` if I don't need to.
![screen shot 2014-08-06 at 12 38 33 pm](https://cloud.githubusercontent.com/assets/253936/3831902/e544263c-1d98-11e4-9d41-f50af8ca8767.png)

**Comment by twmartin** [comment]
YAML code block:
```yaml
- name: This is a test
  key:
    just testing this
    multi-line string
  new_key: hello
```
