### ISSUE TITLE
Keys containing hyphens incorrectly receive 2 colour syntax highlighting

### ISSUE THREAD

**Issue by danbohea** [atom/language-yaml#101]
### Description

Keys containing hyphens incorrectly receive 2 colour syntax highlighting.

### Steps to Reproduce

Example YAML file contents:

```yaml
no_hyphen: "no hyphen example"
single-hyphen: "single hyphen example"
multi-hyphen-example: "multi hyphen example"
```

**Expected behavior:** All keys receive single colour syntax highlighting.

**Actual behavior:** Keys with hyphens receive 2 colour syntax highlighting (one colour up to and including the final hyphen and another colour after the final hyphen).

<img width="444" alt="capita_fork_theme_libraries_yml_ ___projects_client_fivemile_capita-libraries" src="https://user-images.githubusercontent.com/6885065/36097793-52f9d9d2-0ff4-11e8-8016-05290a75ee58.png">

**Reproduces how often:** 100%

### Versions

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.13
git 2.13.3

OS: macOS 10.11.6
