### ISSUE TITLE
Incorrect multiline syntax highlighting |

### ISSUE THREAD

**Issue by burik666** [atom/language-yaml#108]
```yml
values: 
  - foo: |
      hello
      world
    bar: 123
  - foo: value
    bar: 123
```
![atom](https://user-images.githubusercontent.com/1700398/56079899-2e86a680-5e03-11e9-8c4a-2db5e46b6774.png)
