### ISSUE TITLE
Inline objects and arrays are highlighted as strings

### ISSUE THREAD

**Issue by Nixinova** [atom/language-yaml#115]
Removing most of the checklist as I'm not using atom, I'm using the grammar file directly.

This issue is visible on any GitHub file classified as YAML as [Linguist](https://github.com/github/linguist) uses this repository ([scope map](https://github.com/github/linguist/blob/6842d8ccd8f205b4b60abc4657de1a29b243cbe1/grammars.yml#L651-L652), [gitmodule import](https://github.com/github/linguist/blob/6842d8ccd8f205b4b60abc4657de1a29b243cbe1/.gitmodules#L716-L719)) to highlight yaml files.

### Description

The syntax grammar does not apply unique highlighting to inline objects and arrays:

```yaml
---
Key:
  string: some text
  object: { key: value, string: false }
  array: [ string, 10, null ]
```

This syntax is valid and should be shown as such.
