### ISSUE TITLE
Strings that are part of a sequence are highlighted incorrectly if they contain a colon

### ISSUE THREAD

**Issue by rpendleton** [atom/language-yaml#21]
Strings that are part of a sequence are highlighted incorrectly if they contain a colon:

```yaml
assignment: 'Sections 2.4 and 4.1'
problems: 
- 'Section 2.4: 3, 6abc, 12ab, 30, 32a'
- 'Section 4.1: 10ac, 12ab, 13ac, 14ac, 28, 30, 38, 40'
- 'Section 2.4 - 3, 6abc, 12ab, 30, 32a'
- 'Section 4.1 - 10ac, 12ab, 13ac, 14ac, 28, 30, 38, 40'
```
