### ISSUE TITLE
Key for multi-line text in list highlight fail

### ISSUE THREAD

**Issue by brianmhunt** [atom/language-yaml#22]
Given YAML such as:

```yaml
- text: >
    It is much easier to put existing resources to better use than to develop
    resources where they do not exist.
  credit: George Soros
- text: >
    Recognizing the need is the primary condition of design.
  credit: Charles Eames
```

Will appear as, and note the highlight of `credit`:

![screen shot 2015-03-18 at 8 33 54 am](https://cloud.githubusercontent.com/assets/135528/6708749/90d52dba-cd49-11e4-8bb0-3e304ae7ba2e.png)
