### ISSUE TITLE
Highlighting for Multi-Line Text Containing a Leading '#' 

### ISSUE THREAD

**Issue by twmartin** [atom/language-yaml#26]
It seems as though a leading '#' in a line of multi-line text munges the highlighting.

YAML of the form:
```yaml
example: |
  line 1:
  line 2:  # with a comment
  # line 3
  line 4:

```

results in the following highlighting:
<img width="266" alt="screen shot 2015-07-27 at 2 29 45 pm" src="https://cloud.githubusercontent.com/assets/5588240/8915667/fc24cfc4-346b-11e5-9d99-f4ad393b19ff.png">
