### ISSUE TITLE
Syntax highlighting and escaped quotes.

### ISSUE THREAD

**Issue by nbering** [atom/language-yaml#3]
If I use escaped quotes in a string (which I looked up, and is valid in YAML 1.2) the syntax highlighting treats it like normal quotes.  I'd love to include a picture but don't have software for image editing (I just code).  Example use below shows failure in atom.

``` YAML
commands:
  install_app:
    command: "install.php --timezone \"America/New_York\""
```

America/NewYork\

appears in a different color.
