### ISSUE TITLE
Not ignoring ERB tags in quoted string

### ISSUE THREAD

**Issue by ismyrnow** [atom/language-yaml#32]
I have a quoted string which should contain `<%` in it. The result is that the string isn't closed unless a closing ERB tag and closing quote is found.

I'm not sure how you would work around this in the grammar without breaking the ERB highlighting. However, I would consider proper YAML highlight a priority, considering the context.

Example:

```yaml
password: "foo<%bar"
now: highlighting no longer works
close: %>"
now: highlighting works
```

Currently, this also breaks in Github. However, I'll include a screenshot just in case:

![2015-09-03_1113](https://cloud.githubusercontent.com/assets/1127410/9662384/4b99e83a-522d-11e5-8364-b8e6e75c4c59.png)

**Comment by ismyrnow** [comment]
To reduce things even further, all you need to do is close the original quoted string on a new line:

```yaml
password: "foo<%bar"
now: highlighting no longer works
close: "
now: highlighting works
```

The behavior on Github differs here, though.
