### ISSUE TITLE
> and | type multiline strings break syntax highlighting

### ISSUE THREAD

**Issue by alexjurkiewicz** [atom/language-yaml#33]
The following YAML snippet is valid, but syntax highlighting renders incorrectly:

```yaml
key1:
  - subkey1: |
      content

key number 2:
  cmd.run
```

Also works with `>` multiline string type.

Removing spaces from the next string fixes the problem:

```yaml
key1:
  - subkey1: |
      content

key2:
  cmd.run
```

Removing the `|` multiline string indicator works (although this changes the string (no newline at the end)):

```yaml
key1:
  - subkey1:
      content

key number 2:
  cmd.run
```
