### ISSUE TITLE
YAML highlighting broken when colon is inside a quoted string.

### ISSUE THREAD

**Issue by goodevilgenius** [atom/language-yaml#47]
For example, the following code:

```yaml
foo:
    bar: 'ABC: DEF'
    baz: yes
    quux: 0.5
```

If viewing this yaml file, `ABC:` is shown as a quoted string, and the remainder of the line as a bare string. After that line, every subsequent key is highlighted as a quoted string.
