### ISSUE TITLE
Incorrect syntax highlights

### ISSUE THREAD

**Issue by casey-billett** [atom/language-yaml#53]
The following two examples seem to produce the incorrect hightlights -

``` yaml
  roles:
    - { role: common }
    - { role: apache, virtual_host_name: "foo.com", tags: ["apache"] }
    - gitdeploy
    - franklinkim.newrelic



  tasks:
    - git:
        repo='git@github.com:Baz/foo.com.git'
        dest=/var/www/html
        accept_hostkey=yes
        key_file=/var/www/.ssh/id_rsa
```
