### ISSUE TITLE
Comments highlighting error

### ISSUE THREAD

**Issue by zhanzhenzhen** [atom/language-yaml#7]
If a line has a trailing comment, then the comment will be treated as a string.

Code to reproduce:

``` yaml

---
a: 123                     # an integer
b: "123"                   # a string, disambiguated by quotes
c: 123.0                   # a float
d: !!float 123             # also a float via explicit data type prefixed by (!!)
e: !!str 123               # a string, disambiguated by explicit type
f: !!str Yes               # a string via explicit type
g: Yes                     # a boolean True
h: Yes we have No bananas  # a string, "Yes" and "No" disambiguated by context.
```
