### ISSUE TITLE
Alternative boolean representations with wrong highlighting

### ISSUE THREAD

**Issue by Yajo** [atom/language-yaml#81]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom only highlights `true` and `false` as booleans. [YAML has many other ways to write those booleans](http://yaml.org/type/bool.html).

### Steps to Reproduce

Write this:

```yaml
highlight_examples:
    good:
        - true
        - false
    bad:
        - y
        - Y
        - yes
        - Yes
        - YES
        - n
        - N
        - no
        - No
        - NO
        - True
        - TRUE
        - False
        - FALSE
        - on
        - On
        - ON
        - off
        - Off
        - OFF
```

**Expected behavior:** All of those values highlighted as booleans.

**Actual behavior:** Only `true` and `false` work:

![captura de pantalla de 2017-04-25 11-31-57](https://cloud.githubusercontent.com/assets/973709/25378604/d12ac590-29aa-11e7-8640-9f621e0fa537.png)

**Reproduces how often:** 100%

### Versions

```
➤ atom --version
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

➤ apm --version
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.9.3

➤ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 25 (Twenty Five)
Release:	25
Codename:	TwentyFive
```
