### ISSUE TITLE
Wrong coloration for commented multiple line string block

### ISSUE THREAD

**Issue by maxime915** [atom/language-yaml#92]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Editing a .yml file, commenting a multiple line text block will not show correctly (I checked will multiples theme to be sure), this might be an issue of the langage-yml package. To be clear, only the line 
"# blockname: >"  doesn't get gray, all the other line are normally commented, however executing the file, the block is commented, this is juste a presentation issue.

### Steps to Reproduce

1. create a YAML file
2. create a commented block with multiple line, exemple:
```yaml
test:
  path: /path
  defaults:
    _controller: Bundle:Default:Action
  # condition: >
  #   request.headers.get('firstHeader') != null and
  #   request.headers.get('secondHeader') != null and
  #   request.headers.get('thirdHeader') != null
```
3. Look at the wrong coloration

**Expected behavior:**  The first commented line should be also grey

**Actual behavior:** The first commented line is not also grey, it event appear on the web preview

Atom: 
<img width="493" alt="capture d ecran 2017-09-15 a 09 05 51" src="https://user-images.githubusercontent.com/13822908/30470455-1f7d1e5e-99f5-11e7-85df-03c58551b7c4.png">
Web:
<img width="405" alt="capture d ecran 2017-09-15 a 09 05 44" src="https://user-images.githubusercontent.com/13822908/30470454-1f5928b4-99f5-11e7-8c32-211767a7c6ea.png">

**Reproduces how often:** everytime I do it

### Versions

Atom    : 1.19.5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
